### ISSUE TITLE
preg_replace_callback(): Argument #3 ($subject) must be of type array|string, null given

### ISSUE THREAD

**Issue by worldwideweber** [lochmueller/sourceopt#136] opened 2023-10-08 12:12 UTC
If i create a Form Finisher (Redirect to a page), then i get this error.

preg_replace_callback(): Argument #3 ($subject) must be of type array|string, null given

Core: Exception handler (WEB): Uncaught TYPO3 Exception: preg_replace_callback(): Argument #3 ($subject) must be of type array|string, null given | TypeError thrown in file -/vendor/lochmueller/sourceopt/Classes/Service/SvgStoreService.php in line 60.

TYPO3 Version	11.5.22
Webserver	Apache
PHP Version	8.1.23

**Comment by xerc** [comment] 2023-10-08 14:37
seem like you are using a old version of `sourceopt` ; if its ver. > 5.0.1 please add `var_dump($response);`
@ https://github.com/lochmueller/sourceopt/blob/5.1.1/Classes/Middleware/SvgStoreMiddleware.php#L27

**Comment by xerc** [comment] 2023-10-08 15:45
probably duplicate of https://github.com/lochmueller/sourceopt/issues/115

**Comment by lochmueller** [comment] 2023-12-06 14:45
@xerc I would close this issue. 
@worldwideweber If the problem is still open, please create a new issue.

**Closed by lochmueller** 2023-12-06 14:45 UTC
