### ISSUE TITLE
Undefined array key "body"

### ISSUE THREAD

**Issue by Zillion01** [lochmueller/sourceopt#120] opened 2023-04-19 13:22 UTC
`PHP Warning: Undefined array key "body" in /typo3conf/ext/sourceopt/Classes/Service/SvgStoreService.php line 60`

This happens when using the form frame work redirect. 

Reproduce:  make a simple contactform and as a finisher send to a thank you page.

TYPO3 11.5.26
PHP 8.1

**Comment by xerc** [comment] 2023-04-19 13:58
which `sourceopt` version are you using?

**Comment by Zillion01** [comment] 2023-04-19 14:34
5.0.0

I now switched to Powermail, there no problems.

**Comment by Zillion01** [comment] 2023-04-19 14:38
It's typical PHP 8 errors, there you cannot use undefined array keys. But I guess you guys know that. I tried a couple things but then TYPO3 started complaining about other array keys. Not sure what that weird core form extension exactly does ;)

**Comment by lochmueller** [comment] 2023-04-19 14:42
Hey @Zillion01 
I think the problem is already fixed in current master branch.
I will release the current state later today.
Regards,
Tim

**Comment by Zillion01** [comment] 2023-04-19 14:42
Hey mate sounds good thanks

**Comment by lochmueller** [comment] 2023-04-20 20:48
5.0.1 is released (not to TER, but Packagist -> I have to fix the CI pipelines).
I will close this issue.

**Closed by lochmueller** 2023-04-20 20:48 UTC
